### ISSUE TITLE
Add option --preview-metadata for library authors

### ISSUE THREAD

**Issue by Zaid-Ajaj** [Zaid-Ajaj/Femto#14]
Add option `--preview-metadata` is for library authors to check that the XML tags used in the F# project file is actually *parsable* and a npm package version can be calculated . 

### Example usage
```bash
cd MyAwesomeLibrary
cd src
femto --preview-metadata
```

**Comment by Zaid-Ajaj** [comment]
Inspired by [this comment](https://github.com/Zaid-Ajaj/Femto/pull/8#issuecomment-504636057) from @MangelMaxime

**Comment by MangelMaxime** [comment]
I see that as a validation process and propose to name the arg  `--validate`?

This is just a proposition, I do understand why you call it `preview-metadata` but it's a bit long to write ^^. Or perhaps, we could provide `preview-metadata` and an alias `preview`

Also, because we are starting to add several args, I propose to use [Argu](https://github.com/fsprojects/Argu) which is an awesome library for that specific task.

**Comment by Zaid-Ajaj** [comment]
Renamed to `--validate` in #15 
Validation process now checks that
 - `dotnet restore` works against the validated project
 - `ProjectCracker.fullCrack` works against the validated project
 - a version van be resolved based on metadata available in the project

**Comment by Zaid-Ajaj** [comment]
About `Argu` I think it is a bit overkill for now since there only two more options to add:
 - `--auto-resolve`
 - `--json`

**Comment by MangelMaxime** [comment]
Probably, but it's really easy to use and generates the CLI documentation for free.
