### ISSUE TITLE
Detect if the package should be installed as a deps or dev deps

### ISSUE THREAD

**Issue by MangelMaxime** [Zaid-Ajaj/Femto#29]
When uninstalling and installing a package because of a mismatched version we should detect if the package was a deps or dev deps to reinstall it correctly.

We could also ask how to install each deps on having the list using an interactive mode but that less of a problem that the first scenario.

**Comment by Zaid-Ajaj** [comment]
Actually detecting what kind of package it is in `package.json` is not enough because we can't be sure what type it is if it was missing from `package.json`. Also I would like to automate as much as possible without an interactive mode unless user input is really really required. 

This is what propose, extend the XML tags to include what type of dependency it should be, in this case, adding `DevDependency="true"` to determine whether to use `--save` or `--save-dev`. By default `DevDependency` would be `false` 

To implement this, we have to take into account:
 - determine whether an installed package exists in `dependencies` or `devDependencies` 
 - two install commands, one for packages that use `--save` and another for `--save-dev`
 - if a developer installed a `devDependency` in `dependencies` then we need to uninstall it and re-install into `devDependencies` (we can also cheat and modify `package.json` directly but naah...) 

This would enable Femto to do a lot of things:
 - Specify which version of `fable-compiler` your library requires (blocked by resolution conflicts in #21 because multiple libraries will specify multiple `fable-compiler` versions)
 - Specify which *webpack loaders* your library requires (next steps would be to modify webpack.config.js but that is more complicated for now)

What do you think?

**Comment by MangelMaxime** [comment]
I thought about `DevDependency="true"` when proposing this issue but I am not sure that we can 100% define that at the library level. Because this is something related to how the user sees its env and bundle the project.

>     * if a developer installed a `devDependency` in `dependencies` then we need to uninstall it and re-install into `devDependencies` (we can also cheat and modify `package.json` directly but naah...)

This is the scenario I don't like because potentially the developer had his a reason to put it as a `dependencies` and not as a `devDependency`.

For example, for Bulma, it can be either a `devDependency` if you bundle using `sass` or a `dependency` if the user is serving the `css` files directly from the `node_modules`.

I always found it really hard/confusing to determine if a package should go to `devDependencies` or `dependencies` list.

>     * Specify which version of `fable-compiler` your library requires (blocked by resolution conflicts in #21 because multiple libraries will specify multiple `fable-compiler` versions)

I am sure I don't want a library to control my `fable-compiler` version. This seems like a source of bugs/problems to me.

At least, in the first stage of this tool, I would like us to not encourage/do it.

>     * Specify which _webpack loaders_ your library requires (next steps would be to modify webpack.config.js but that is more complicated for now)

I don't want a tool to touch my `webpack.config.js` because my `webpack.config.js` is heavily modified to correspond to my project needs like API redirection, HTTPS cert, copy of assets, etc. And there is "no way" that a tool can modify it correctly.

Also, you can't know which loader is needed for a library. For example, Fulma can ask the user to use:
- MiniCssExtractPlugin
- 'style-loader'
- 'css-loader'
- 'sass-loader'

But if the person doesn't use `sass` files them this doesn't make sense.

IHMO Femto should be specialized in one thing only which is:

> verifies the compatibility of npm packages used by Fable bindings.

From a personal point of view, if a tool is trying to do everything, in general, I don't use it because in general, I end up fighting it just like when a library is trying to do everything for you.

**Comment by Zaid-Ajaj** [comment]
I totally understand what you are saying, personally I don't like "god tools" and this discussion is more of "More control and do it yourself approach vs. Less control and let Femto do it" 

My suggestions are coming from two assumptions:
 -  A lot of Fable users, especially beginners would like Fable packages to "just work" without having to make decisions about the dependencies 
 - Library authors "know more" about their dependencies that's why I wanted to automate as much as possible even if I personally want to configure everything myself 

### Dependencies vs DevDependencies 

> This is the scenario I don't like because potentially the developer had his a reason to put it as a > dependencies and not as a devDependency. 

> For example, for Bulma, it can be either a devDependency if you bundle using sass or a dependency if > the user is serving the css files directly from the node_modules.

Please correct me if I am wrong, in case of Bulma, you could still serve the css directly from `node_modules` even if it was a `devDependency` no? AFAIK the `require` mechanism is the same both for `dependencies` and `devDependencies` so putting bulma in either sections should have the same results right?

Again, my assumption here is that *you*, the author of the library know more about where the dependency should go (dep vs. dev dep) in most common cases

### Versioning fable-compiler

> I am sure I don't want a library to control my fable-compiler version. This seems like a source of bugs/problems to me.

Yeah maybe not a good idea, I am just thinking out loud and wondered what you though about it

### Webpack loaders and modifications 

I know there is no way to know how every developer is using `webpack.config.js` but I am talking more about most common use-cases, maybe not modify the file but just *check* that there is at least some style loaders being used, giving a warning to developer otherwise if that is not the case

There are reliable ways of doing this: reading the javascript AST using something like [esprima-dotnet](https://github.com/sebastienros/esprima-dotnet) of webpack.config.js and analyzing the configuration. 

This was inspired by vue-cli which even hides the webpack config file from the developer but uses it under the hood, probably not what Femto should be concerned with

### Purpose of Femto

> IHMO Femto should be specialized in one thing only which is: verifies the compatibility of npm packages used by Fable bindings.

💯 agree

**Comment by MangelMaxime** [comment]
> Please correct me if I am wrong, in case of Bulma, you could still serve the css directly from `node_modules` even if it was a `devDependency` no? AFAIK the `require` mechanism is the same both for `dependencies` and `devDependencies` so putting bulma in either sections should have the same results right?
> 
> Again, my assumption here is that _you_, the author of the library know more about where the dependency should go (dep vs. dev dep) in most common cases

The difference between `dependencies` and `devDependencies` is that in production env (when you set `NODE_ENV=production`) then `npm` and `yarn` will not install the `devDependencies` so they will not be present in the `node_modules`.

Even, if in general, people should not serve files from `devDependencies` because the files should be a bundle.

> Yeah maybe not a good idea, I am just thinking out loud and wondered what you though about it

No problem, all I say is for thinking and discussing together too even if sometimes it's hard not look aggressive etc. when writing  :)

> Webpack loaders and modifications

For me this is out of the scope of Femto. I know that people on the SAFE stack wants to create a CLI tool to upgrade, scaffold SAFE application and I think this section should be in that tool if created one day.

> ### Purpose of Femto
> 
> > IHMO Femto should be specialized in one thing only which is: verifies the compatibility of npm packages used by Fable bindings.
> 
> 💯 agree

I 💯 agree with your 💯 agree ;)

Let focused on a simple task right now and if needed extend Femto if the feature is still in its scope :)

---------------------

To come back to the original discussion let's try adding `DevDependency="true"` attribute support. It seems like the Bulma documentation say to install it using `npm install bulma` so as a dependency. 

If this proves to be a problem in the future, we will think of a way to solve it. For example,

- Remove complete support for `DevDependency` attribute
- Or in case of conflict ask the user what to do

**Comment by Zaid-Ajaj** [comment]
Awesome! it's settled then, I will start implementing both the `DevDependency` feature and fix #21 along the way :smile:
