### ISSUE TITLE
Remove InstallHint property

### ISSUE THREAD

**Issue by MangelMaxime** [Zaid-Ajaj/Femto#3]
If I understand correctly the README, the hint is "static" and is determined using `InstallHint="npm install date-fns@1.30"`

I think we could remove the `InstallHint` parameter because we already have all the infos needed to generate it.

1. Detect if the project is using `yarn` or `npm`. If the repo contains a `yarn.lock` then it's using `yarn`
2. Extract the version from `>= 1.30.0`
3. Generates `{Command} install {Package}@{Version}`

**Comment by Zaid-Ajaj** [comment]
I wanted to that at first, just generate the install message or even install the required version directly but the problem is that the `Version` you specify in .fsproj is not really an exact version; it is a *range* of versions (i.e. `>= 1.30.0`) 

Using a range you can check whether the installed library (exact) version [satisfies](https://github.com/Zaid-Ajaj/Femto/blob/master/Program.fs#L147) the range:
```fs
match pkg.Constraint with
| Some requiredRange when requiredRange.IsSatisfied version ->
```
Which is why I need the author to which *exact* version he/she needs that satisfies the required range. 

That optimal way to solving this problem is by calculating the *minimum* version that satisfies the required range
```
minVersion ">= 1.30.0" // 1.30.0
```
Then use that minimum version to generate the install hint but the library [SemanticVersioning](https://github.com/adamreeve/semver.net) didn't have this functionality, so I need to calculate it myself

**Comment by MangelMaxime** [comment]
Ok, I think I have an idea on how to solve this problem.

**Comment by Zaid-Ajaj** [comment]
Yeah me too :wink: looks like we just need to parse the output of `npm show <package> versions` then get the minimum version of it, were you thinking of the same thing?

**Comment by MangelMaxime** [comment]
F*ck, I wanted to cancel my PR because I saw your answer here and I clicked on create...

Whatever, I closed my PR.

My idea was to request NPM registry in order to get all the versions available for a library and then take the `maxSatisfiying` one.

I didn't know about `npm show <package> versions --json`  which in this case can be better, because `npm` will be responsible of resolving the registry host :)

I can redo my PR using your solution instead. :)

**Comment by Zaid-Ajaj** [comment]
> I can redo my PR using your solution instead. :)

Sorry about that :/ I can do it if you don't want to rewrite stuff you already did 

> and then take the maxSatisfiying one.

Choosing either `maxSatisfying` or `minSatisfying` should be an option, just like paket's [resolver strategy](https://fsprojects.github.io/Paket/dependencies-file.html#Resolver-strategy-for-transitive-dependencies) But I would like to make it the `minSatisfying` the *default* option such that it the "closest" to what the binding expects. If a library says I want `date-fns >= 1.30.0` then the tool will return `1.30.1` as the exact version, not 2.x

**Comment by MangelMaxime** [comment]
> Sorry about that :/ I can do it if you don't want to rewrite stuff you already did

No problem, I opened to PR to discuss my ideas and was consider that it still had work to do. 

I will create a new PR using your solution and taking into account your comments.
