### ISSUE TITLE
Work with paket.dependencies

### ISSUE THREAD

**Issue by nojaf** [Zaid-Ajaj/Femto#46]
Hi @Zaid-Ajaj , in my current setup I'm not using an fsproj but an [fsharp script in combination with Paket](https://axxes.com/en/net/compiling-f-scripts-with-fable-2-2/).

It would be nice if femto can look at my `paket.dependencies` and figure it out.
For example:
```
source https://www.nuget.org/api/v2
storage:none
framework:netstandard2.0

nuget Fable.React
```

**Comment by Zaid-Ajaj** [comment]
Hello Florian,

This might actually prove difficult to accomplish because Femto currently doesn't look at paket.dependencies because that would only give the *direct* dependencies and we need the *transitive* ones. Of course we can parse the lock file to get the transitive dependencies as well but that is not enough because we still need to locate the actual source code of the required Fable packages in order to parse the metadata from the project file. 

To get all of the dependencies, the direct and the transitive, Femto relies entirely on the [project cracker](https://github.com/Zaid-Ajaj/Femto/blob/master/ProjectCoreCracker.fs) which as far as I know, is only relevant for projects. 

Femto is now beta and before implementing such feature I would like to prioritize the work to get it into a stable release which involves much needed work around getting core libraries to support Femto, especially most used ones like `Fable.Elmish.React` and `Fable.React`, please take a look at [this issue](https://github.com/elmish/react/issues/43).

**Comment by nojaf** [comment]
Hi, what if we parse an fsx  file instead?
[Similar to how Fable does this.](https://github.com/fable-compiler/Fable/blob/master/src/Fable.Cli/ProjectCracker.fs#L125)

**Comment by Zaid-Ajaj** [comment]
Oh if that already gives us a `CrackedProject` then that's all we need to get it up and running with Femto :smile: PR maybe?

**Comment by nojaf** [comment]
Looks like it is [almost](https://github.com/Zaid-Ajaj/Femto/blob/master/ProjectCracker.fs#L52) already there 😋.
I'll try to create a PR in the coming weeks.

**Comment by Zaid-Ajaj** [comment]
Heyy @nojaf any (planned) progress on this one? :smile:

**Comment by nojaf** [comment]
Hey Zaid, I sorta lost track of this. Nothing planned for the moment. Maybe close this issue and let's reopen if other people are interested.

**Comment by Zaid-Ajaj** [comment]
Sounds good to me :smile: Thanks for quick reply
