### ISSUE TITLE
Femto v0.5.2 getPackageVersions fails when using yarn v1.16.0

### ISSUE THREAD

**Issue by Zaid-Ajaj** [Zaid-Ajaj/Femto#53]
Running `femto` or `femto --resolve` doesn't seem to work with yarn as of latest version of Femto 0.5.2, the function [getPackageVersions](https://github.com/Zaid-Ajaj/Femto/blob/master/Program.fs#L165) fails retrieving the package information. 

The problem can be reproduced by starting from a fresh SAFE template, adding a package with Femo-compatible metadata (Elmish.SweetAlert, Feliz etc.) and running femto against the Client project. 

@MangelMaxime can you please confirm whether such problem occurs with you as well? I have yarn 1.16.0 installed

**Comment by MangelMaxime** [comment]
I wasn't able to test it against SAFE template because I have no idea how to run paket in it. 

So I tested it against `fulma-minimal`:

1. `dotnet new -i Fable.Template.Fulma.Minimal`
2. `dotnet new fulma-minimal -lang F#`
3. Add `Elmish.SweetAlert` by editing paket files
4. Run `paket update`
5. Run `femto`
6. It works

I tested it with my old version of yarn which was something like `1.12.x` and the latest `1.17.3` and it works fine.

*I tried to install `1.16.0` via `brew` but I didn't succeed*

So I guess it's a problem on your side or something was broken in the previous version of yarn and they fixed it.

**Comment by Zaid-Ajaj** [comment]
Thanks @MangelMaxime for checking, I guess I can assume Femto doesn't work for newer versions of yarn, it might have something to do with the exit code that yarn returns, I will check

**Comment by MangelMaxime** [comment]
> I guess I can assume Femto doesn't work for newer versions of yarn

I tested with the latest version `1.17.3` so no you can't assume that :) Unless, my reproduction is wrong.

**Comment by Zaid-Ajaj** [comment]
@MangelMaxime Looks like I can't read properly today :joy: OK I will assume it doesn't work on my machine for yarn 1.16 which is fine!

**Comment by Zaid-Ajaj** [comment]
I figured it out, in the code we check whether the `Error` of yarn process is empty but on my windows it is not empty: it shows a warning about an API being experimental, it is an easy fix.
