### ISSUE TITLE
Femto as a local tool?

### ISSUE THREAD

**Issue by halcwb** [Zaid-Ajaj/Femto#66]
I think the use of global tools with dotnet will be [deprecated](https://github.com/fsharp/FAKE/issues/2465). Will this apply to femto as well?

**Comment by Zaid-Ajaj** [comment]
Hi Casper, 

Femto already supports being installed as a local dotnet tool. You can install it locally in your project/solution like this
```
dotnet new tool-manifest
dotnet tool install femto 
```
then use it with dotnet
```
dotnet femto {args}
```

**Comment by halcwb** [comment]
Ok, great. So, this should be the recommended way?

**Comment by Zaid-Ajaj** [comment]
Yeah I can add it to the docs to show how to install as a local tool but that doesn't mean that global tools are going away any time soon. Especially in the context of Femto, it makes sense to use it as a global tool on development machines because the functionality is not specific to a single project
