### ISSUE TITLE
Use pnpm instead of npm

### ISSUE THREAD

**Issue by adelarsq** [Zaid-Ajaj/Femto#74]
It's possible to configure Femto to use [PNPM](https://pnpm.js.org/) instead of NPM?

**Comment by Zaid-Ajaj** [comment]
It is possible to add this the same way Femto detects yarn using its lock file. So if a repository has `pnpm-lock.yaml` we could add make the installation commands execute against `pnpm` instead. However, I am not sure if `pnpm list --json` works because that would be how we determine which packages are installed locally since pnpm will not write all packages to `node_modules`. 

I don't have a timeline to implement this, though PRs are more than welcome. This would be blocked by #73 since fixing that would go first

**Comment by adelarsq** [comment]
> It is possible to add this the same way Femto detects yarn using its lock file. So if a repository has `pnpm-lock.yaml` we could add make the installation commands execute against `pnpm` instead. However, I am not sure if `pnpm list --json` works because that would be how we determine which packages are installed locally since pnpm will not write all packages to `node_modules`.

Nice!
 
> I don't have a timeline to implement this, though PRs are more than welcome. This would be blocked by #73 since fixing that would go first

Thanks @Zaid-Ajaj. I will try to help on this.

**Comment by adelarsq** [comment]
@Zaid-Ajaj Thanks! I forgot to answer. It's working!

**Comment by Zaid-Ajaj** [comment]
@adelarsq Awesome! thanks for confirming 🙏
